import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Search, Users } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export const Route=createFileRoute("/admin/customers")({component:AdminCustomers});
type CustomerSummary={id:string;full_name:string;phone:string;email:string|null;created_at:string;orders:number;spent:number;last_order:string|null};
function AdminCustomers(){const[customers,setCustomers]=useState<CustomerSummary[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{let cancelled=false;void supabase.rpc("admin_customer_summaries").then(({data,error:rpcError})=>{if(cancelled)return;if(rpcError)setError(rpcError.message||"Unable to load customer data.");else setCustomers((data??[]) as CustomerSummary[]);setLoading(false)});return()=>{cancelled=true}},[]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return customers.filter(c=>!q||c.full_name.toLowerCase().includes(q)||c.phone.toLowerCase().includes(q)||(c.email??"").toLowerCase().includes(q))},[customers,query]);return <div className="space-y-6"><div><p className="text-sm font-medium text-muted-foreground">Commerce</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Customers</h2><p className="mt-2 text-muted-foreground">Live customer records with order history and spending totals from the existing Supabase checkout data.</p></div><Card><CardHeader className="gap-4 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>All customers</CardTitle><CardDescription>{loading?"Loading customers...":`${filtered.length} of ${customers.length} customers`}</CardDescription></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone or email" className="pl-9"/></div></CardHeader><CardContent>{error?<p className="text-sm text-destructive">{error}</p>:loading?<p className="py-8 text-sm text-muted-foreground">Loading customers…</p>:filtered.length===0?<p className="py-8 text-sm text-muted-foreground">No customers found yet.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="border-b text-left text-muted-foreground"><tr><th className="pb-3 font-medium">Customer</th><th className="pb-3 font-medium">Phone</th><th className="pb-3 font-medium">Email</th><th className="pb-3 font-medium">Orders</th><th className="pb-3 font-medium">Total spent</th><th className="pb-3 font-medium">Last order</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} className="border-b last:border-0"><td className="py-4 font-medium"><span className="inline-flex items-center gap-2"><Users className="size-4 text-muted-foreground"/>{c.full_name}</span></td><td className="py-4">{c.phone}</td><td className="py-4">{c.email||"—"}</td><td className="py-4">{Number(c.orders)}</td><td className="py-4 font-medium">KSh {Number(c.spent).toLocaleString()}</td><td className="py-4 text-muted-foreground">{c.last_order?new Date(c.last_order).toLocaleDateString():"No orders"}</td></tr>)}</tbody></table></div>}</CardContent></Card></div>}
