import { createFileRoute, Link, Outlet, redirect, useLocation, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CreditCard, FolderTree, LayoutDashboard, LogOut, Menu, Package, ReceiptText, Users, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const Route = createFileRoute("/admin")({ beforeLoad: async ({ location }) => { if (location.pathname === "/admin/login") return; const { data: { session } } = await supabase.auth.getSession(); if (!session) throw redirect({ to: "/admin/login" }); const { data: isAdmin, error } = await supabase.rpc("is_admin"); if (error || !isAdmin) { await supabase.auth.signOut({ scope: "local" }); throw redirect({ to: "/admin/login" }); } }, component: AdminRoute });
const items=[{label:"Dashboard",to:"/admin",icon:LayoutDashboard},{label:"Products",to:"/admin/products",icon:Package},{label:"Categories",to:"/admin/categories",icon:FolderTree},{label:"Orders",to:"/admin/orders",icon:ReceiptText},{label:"Customers",to:"/admin/customers",icon:Users},{label:"Payments",to:"/admin/payments",icon:CreditCard}] as const;
function AdminRoute(){const location=useLocation();if(location.pathname==="/admin/login")return <Outlet/>;return <AdminShell><Outlet/></AdminShell>}
function AdminShell({children}:{children:React.ReactNode}){const navigate=useNavigate();const location=useLocation();const [menu,setMenu]=useState(false);const [loggingOut,setLoggingOut]=useState(false);const [logoutError,setLogoutError]=useState("");async function logout(){if(loggingOut)return;setLoggingOut(true);setLogoutError("");try{const {error}=await supabase.auth.signOut({scope:"local"});if(error)throw error;await navigate({to:"/admin/login",replace:true})}catch{setLogoutError("Unable to sign out. Please try again.")}finally{setLoggingOut(false)}}const nav=<nav className="space-y-1">{items.map(item=>{const Icon=item.icon;const active=location.pathname===item.to;return <Link key={item.to} to={item.to} onClick={()=>setMenu(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${active?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="size-5"/>{item.label}</Link>})}</nav>;return <div className="min-h-screen bg-muted/30"><aside className="fixed inset-y-0 left-0 z-40 hidden w-72 border-r bg-background lg:block"><div className="flex h-full flex-col p-4"><div className="px-2 py-5"><p className="font-display text-lg font-semibold">SCENTLYN</p><p className="text-xs text-muted-foreground">Laundrymart Admin</p></div>{nav}<p className="mt-auto px-2 text-xs text-muted-foreground">Phase 1 · Read-only</p></div></aside>{menu&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/20" onClick={()=>setMenu(false)} aria-label="Close navigation"/><aside className="relative h-full w-72 bg-background p-4"><div className="mb-3 flex justify-end"><Button variant="ghost" size="icon" onClick={()=>setMenu(false)}><X className="size-5"/></Button></div>{nav}</aside></div>}<div className="lg:pl-72"><header className="sticky top-0 z-30 flex min-h-16 items-center justify-between border-b bg-background px-4 sm:px-6"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setMenu(true)}><Menu className="size-5"/></Button><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Scentlyn Laundrymart</p><h1 className="font-display font-semibold">Admin</h1></div></div><div><Button variant="outline" onClick={logout} disabled={loggingOut} className="gap-2"><LogOut className="size-4"/>{loggingOut?"Signing out...":"Logout"}</Button>{logoutError&&<p className="mt-1 text-xs text-destructive">{logoutError}</p>}</div></header><main className="mx-auto w-full max-w-7xl p-4 sm:p-6 lg:p-8">{children}</main></div></div>}
function AdminDashboard(){const [stats,setStats]=useState({products:0,categories:0,orders:0,revenue:0,loading:true});useEffect(()=>{let stop=false;void Promise.all([supabase.from("products").select("id",{count:"exact",head:true}),supabase.from("categories").select("id",{count:"exact",head:true}),supabase.from("orders").select("id",{count:"exact",head:true}),supabase.from("payments").select("amount,status")]).then(([p,c,o,pay])=>{if(stop)return;const revenue=(pay.data??[]).filter(x=>x.status==="paid").reduce((s,x)=>s+Number(x.amount??0),0);setStats({products:p.count??0,categories:c.count??0,orders:o.count??0,revenue,loading:false})});return()=>{stop=true}},[]);const cards=[{title:"Products",value:stats.products,description:"Products in catalogue"},{title:"Categories",value:stats.categories,description:"Categories in catalogue"},{title:"Orders",value:stats.orders,description:"Orders recorded"},{title:"Revenue",value:`KSh ${stats.revenue.toLocaleString()}`,description:"Paid payments recorded"}];return <><Badge variant="secondary">Phase 1 · Read-only</Badge><h2 className="mt-3 text-3xl font-semibold">Welcome back</h2><p className="mt-2 text-muted-foreground">Live overview data from your Scentlyn Supabase project.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=><Card key={card.title}><CardHeader><CardTitle>{card.title}</CardTitle><CardDescription>{card.description}</CardDescription></CardHeader><CardContent><p className="text-2xl font-semibold">{stats.loading?"—":card.value}</p></CardContent></Card>)}</section></>}
