import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Search, Users } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
export const Route=createFileRoute("/admin/customers")({component:AdminCustomers});
type Customer={id:string;full_name:string;phone:string;email:string|null;created_at:string};
function AdminCustomers(){const[customers,setCustomers]=useState<Customer[]>([]);const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{let cancelled=false;void supabase.from("customers").select("id,full_name,phone,email,created_at").order("created_at",{ascending:false}).then(({data,error})=>{if(cancelled)return;if(error)setError(error.message||"Unable to load customers.");else setCustomers((data??[]) as Customer[]);setLoading(false)});return()=>{cancelled=true}},[]);const filtered=customers.filter(c=>{const q=query.trim().toLowerCase();return!q||c.full_name.toLowerCase().includes(q)||c.phone.toLowerCase().includes(q)||(c.email??"").toLowerCase().includes(q)});return <div className="space-y-6"><div><p className="text-sm font-medium text-muted-foreground">Commerce</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Customers</h2><p className="mt-2 text-muted-foreground">Live customer records from Supabase, shared with the checkout and order system.</p></div><Card><CardHeader className="gap-4 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>All customers</CardTitle><CardDescription>{loading?"Loading customers...":`${filtered.length} of ${customers.length} customers`}</CardDescription></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone or email" className="pl-9"/></div></CardHeader><CardContent>{error?<p className="text-sm text-destructive">{error}</p>:loading?<p className="py-8 text-sm text-muted-foreground">Loading customers…</p>:filtered.length===0?<p className="py-8 text-sm text-muted-foreground">No customers found yet.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="border-b text-left text-muted-foreground"><tr><th className="pb-3 font-medium">Customer</th><th className="pb-3 font-medium">Phone</th><th className="pb-3 font-medium">Email</th><th className="pb-3 font-medium">Joined</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} className="border-b last:border-0"><td className="py-4 font-medium"><span className="inline-flex items-center gap-2"><Users className="size-4 text-muted-foreground"/>{c.full_name}</span></td><td className="py-4">{c.phone}</td><td className="py-4">{c.email||"—"}</td><td className="py-4 text-muted-foreground">{new Date(c.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</CardContent></Card></div>}
