import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Check, ChevronRight, MessageCircle, Minus, Plus, ShieldCheck, Truck } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { toast } from "sonner";

import { ProductCard } from "@/components/product-card";
import { Button } from "@/components/ui/button";
import { useCart } from "@/lib/cart";
import { getCatalogue } from "@/lib/catalogue";
import { formatPrice, subcategoryName, waLink } from "@/lib/shop-data";

export const Route = createFileRoute("/product/$slug")({
  loader: async ({ params }) => { const catalogue = await getCatalogue(); const product = catalogue.products.find((p) => p.slug === params.slug); if (!product) throw notFound(); return { product, category: catalogue.categories.find((c) => c.slug === product.category) ?? null, related: catalogue.products.filter((p) => p.slug !== product.slug && p.category === product.category).slice(0, 4) }; },
  head: ({ loaderData }) => { if (!loaderData) return { meta: [{ title: "Product unavailable — Scentlyn" }, { name: "robots", content: "noindex" }] }; const title = `${loaderData.product.name} — Scentlyn`; return { meta: [{ title }, { name: "description", content: loaderData.product.short }, { property: "og:title", content: title }, { property: "og:description", content: loaderData.product.short }, { property: "og:image", content: loaderData.product.image }] }; },
  component: ProductPage,
});

function ProductPage() {
  const { product, category, related } = Route.useLoaderData(); const { add } = useCart(); const firstAvailable = product.variants.findIndex((v) => v.inStock); const [variantIndex, setVariantIndex] = useState(firstAvailable === -1 ? 0 : firstAvailable); const [qty, setQty] = useState(1); const variant = product.variants[variantIndex]; const selectedImage = (variant as typeof variant & { image?: string } | undefined)?.image || product.image; const variantStock = variant?.inStock ? Math.max(0, Number((variant as typeof variant & { stockQuantity?: number }).stockQuantity ?? 0)) : 0;
  useEffect(() => { setQty(1); }, [variantIndex]);
  if (!variant || !category) return null;
  const maxQty = variantStock > 0 ? variantStock : 1;
  const waMessage = `Hi Scentlyn, I'd like to enquire about ${product.name} – ${variant.label}. Is it available?`;
  return <div className="bg-background"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <nav aria-label="Breadcrumb" className="flex items-center gap-1 text-xs text-muted-foreground"><Link to="/" className="hover:text-foreground">Home</Link><ChevronRight className="h-3 w-3" aria-hidden="true" /><Link to="/category/$category" params={{ category: category.slug }} className="hover:text-foreground">{category.name}</Link><ChevronRight className="h-3 w-3" aria-hidden="true" /><span className="max-w-[180px] truncate text-foreground" aria-current="page">{product.name}</span></nav>
    <div className="mt-6 grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:gap-14"><div className="lg:sticky lg:top-24 lg:self-start"><div className="relative overflow-hidden rounded-xl border border-border bg-surface"><img src={selectedImage} alt={`${product.name} — ${variant.label}`} width="800" height="800" fetchPriority="high" className="aspect-square w-full object-cover" />{product.brand === "Scentlyn" && <span className="absolute left-4 top-4 rounded-lg bg-background/90 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-brand">Scentlyn</span>}</div><p className="mt-3 text-center text-xs text-muted-foreground">Selected option: {variant.label}</p></div>
      <div className="py-1 lg:py-4"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-brand">{product.brand || subcategoryName(product.category, product.subcategory)}</p><h1 className="mt-3 font-display text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">{product.name}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-muted-foreground sm:text-base">{product.short}</p>
        <div className="mt-6 flex flex-wrap items-end gap-x-4 gap-y-2 border-b border-border pb-6"><span className="font-display text-3xl font-bold text-brand">{formatPrice(variant.price)}</span>{variant.compareAtPrice && variant.compareAtPrice > variant.price && <span className="text-sm text-muted-foreground line-through">{formatPrice(variant.compareAtPrice)}</span>}<span className={`text-sm ${variant.inStock ? "text-primary" : "text-muted-foreground"}`}>{variant.inStock ? "In stock" : "Currently unavailable"}</span></div>
        <div className="mt-7"><div className="flex items-center justify-between gap-4"><h2 className="text-sm font-semibold">{product.variantLabel}</h2><span className="text-xs text-muted-foreground">{product.variants.length} options</span></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{product.variants.map((v, i) => <button key={v.label} type="button" onClick={() => setVariantIndex(i)} disabled={!v.inStock} aria-pressed={i === variantIndex} className={`min-h-12 rounded-lg border px-3 py-2 text-left text-sm font-medium transition-[transform,background-color,border-color] duration-200 ease-[cubic-bezier(0.22,1,0.36,1)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 ${i === variantIndex ? "border-primary bg-accent text-accent-foreground" : "border-border bg-background hover:bg-secondary active:scale-[0.99]"} disabled:cursor-not-allowed disabled:opacity-40`}><span className="block truncate">{v.label}</span><span className="mt-0.5 block text-xs font-normal opacity-70">{formatPrice(v.price)}</span></button>)}</div></div>
        <div className="mt-7 flex flex-col gap-3 sm:flex-row sm:items-end"><div><label className="mb-2 block text-xs font-semibold uppercase tracking-[0.14em]" htmlFor="quantity">Quantity</label><div className="flex h-12 items-center rounded-lg border border-border"><button type="button" aria-label="Decrease quantity" disabled={qty <= 1} onClick={() => setQty((q) => Math.max(1, q - 1))} className="flex h-full w-12 items-center justify-center hover:bg-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-40"><Minus className="h-4 w-4" /></button><output id="quantity" className="w-10 text-center text-sm font-semibold" aria-live="polite">{qty}</output><button type="button" aria-label="Increase quantity" disabled={!variant.inStock || qty >= maxQty} onClick={() => setQty((q) => Math.min(maxQty, q + 1))} className="flex h-full w-12 items-center justify-center hover:bg-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-40"><Plus className="h-4 w-4" /></button></div>{variant.inStock && <p className="mt-1.5 text-xs text-muted-foreground">{variantStock} available</p>}</div><Button variant="brand" size="xl" className="flex-1" disabled={!variant.inStock} onClick={() => { add({ productSlug: product.slug, name: product.name, variant: variant.label, unitPrice: variant.price, quantity: qty, image: selectedImage }, maxQty); toast.success(`${product.name} added to cart`, { description: variant.label }); }}>Add to basket</Button></div>
        <Button asChild variant="whatsapp" size="xl" className="mt-3 w-full"><a href={waLink(waMessage)} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4" /> Ask about this product on WhatsApp</a></Button>
        <div className="mt-8 grid gap-3 sm:grid-cols-2"><InfoItem icon={<Truck className="h-4 w-4" />} title="Delivery across Kenya" text="Nairobi delivery from KSh 250 · countrywide courier available." /><InfoItem icon={<ShieldCheck className="h-4 w-4" />} title="Shop with confidence" text="Genuine products and sealed packaging." /></div>
        <div className="mt-8 border-t border-border pt-7"><h2 className="font-display text-xl font-bold">About this product</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{product.description}</p>{product.benefits.length > 0 && <ul className="mt-5 space-y-3">{product.benefits.map((benefit) => <li key={benefit} className="flex gap-3 text-sm text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{benefit}</li>)}</ul>}</div>
      </div></div>
    {related.length > 0 && <section className="mt-16 border-t border-border pt-12"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-brand">Keep exploring</p><h2 className="mt-2 font-display text-2xl font-bold sm:text-3xl">You may also like</h2></div><Link to="/category/$category" params={{ category: category.slug }} className="hidden text-sm font-semibold text-brand hover:underline sm:block">Shop {category.name}</Link></div><div className="mt-7 grid grid-cols-2 gap-x-3 gap-y-7 sm:grid-cols-3 lg:grid-cols-4 lg:gap-x-6">{related.map((p) => <ProductCard key={p.slug} product={p} />)}</div></section>}
  </div></div>;
}

function InfoItem({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="rounded-xl border border-border bg-surface/50 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><span className="text-primary">{icon}</span>{title}</div><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{text}</p></div>; }
